name: service-build-push

on:
  push:
    tags:
      - 'service-template/*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test
    uses: Neosofia/platform-workflows/.github/workflows/_test-python.yml@main

  scan:
    name: Vulnerability Scan
    uses: Neosofia/platform-workflows/.github/workflows/_scan.yml@main

  build-push:
    name: Build & Push to GHCR
    needs: [test, scan]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Log in to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ghcr.io/${{ github.repository_owner }}/service-template
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}
            type=match,pattern=service-template/(.*),group=1

      - name: Build and push image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=service-template
          cache-to: type=gha,scope=service-template,mode=max
